---
title: "Exe. 5"
output:
  pdf_document: default
  github_document: default
---

# Simple vs complex

The general concept of transmission is that an idea, illness, or  other trait can be spread to a group by connecting with the person who originally had the infection and passing it through a  group. Transmission can be divided into two groups: simple transmission and complex transmission. A simple infection is  like a cold, it's very easy to get, and you just need to get along with the person who caught the cold. Ultimately, as long as everyone on the network is connected by at least one link, everyone on the network will be cold (for example, if there are no subgroups that are not connected to other isolated communities). ). The idea here is to spread or "cascade" information  through  connected groups. Complex transmissions, on the other hand, can easily be described as ideas or beliefs that can  spread throughout the group. However, the difference between  simple transmissions is that certain thresholds need to be reached for the idea to spread throughout the network. The threshold is defined as the percentage of people's connections that everyone needs to believe in  an idea in order for a person to participate (catch an idea). Another idea is that a person needs to be presented with an idea many times before he or she can accept it. The problem here is that  enough connections between groups and ideas cannot be easily propagated, more connections and  ideas can be propagated quickly, and too many will reduce the number of connections connected to it. Therefore, the idea cannot be propagated.

# Organization

From an organizational point of view, it is important to understand complex diffusion. This is because information is a natural way to travel within an organization. Depending on the structure of the connections within the organization, complex transmission concepts can prevent important (and should be disseminated within the group) information from penetrating certain parts of the organization. If one group of companies connects only  to the remaining groups on a weekly basis (below the transmission threshold), this information cannot penetrate that group and can be detrimental. As explained above, the reverse is also true. If the group is very connected and ideas / actions / information can only be obtained from one source (the leader who leads the team), then the existing connections will be  diluted by extreme interconnections, so join the group. Is very difficult. Understanding how your organization's connections  and  information travel within your organization can help you decide how to change / direct group behavior. This is done by choosing who to approach / participate first in order to successfully implement the idea / action / information.

# Threshold

Understanding the thresholds for positive / negative behavior and the spread of  new ideas (learning)  can help you take proactive steps to change the structure of your organization to  promote or stop its spread. For things like learning, this can be done by introducing new ideas to specific key people or  groups of people. Stopping bad behavior  can be more complicated as it involves breaking connections (moving people between departments, dismissing, etc.). This can be more complicated than introducing an idea or making  a new connection at a particular point. In new departments, ideas may spread there instead.
